export const NUTRITION_DB: Record<
  string,
  {
    calories: number;
    protein: number;
    carbs: number;
    fat: number;
    sugar: number;
    fibre: number;
    avgPortionGrams: number;
    allergens: string[];
  }
> = {
  samosa: {
    calories: 308,
    protein: 5.5,
    carbs: 32,
    fat: 17,
    sugar: 2,
    fibre: 2.5,
    avgPortionGrams: 60,
    allergens: ["wheat"],
  },
  idli: {
    calories: 120,
    protein: 4,
    carbs: 22,
    fat: 1,
    sugar: 0.5,
    fibre: 1.5,
    avgPortionGrams: 40,
    allergens: [],
  },
  dosa: {
    calories: 168,
    protein: 4,
    carbs: 28,
    fat: 4,
    sugar: 1,
    fibre: 1.8,
    avgPortionGrams: 80,
    allergens: [],
  },
  rice: {
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    sugar: 0,
    fibre: 0.4,
    avgPortionGrams: 150,
    allergens: [],
  },
  dal: {
    calories: 116,
    protein: 9,
    carbs: 16,
    fat: 1.5,
    sugar: 1,
    fibre: 5,
    avgPortionGrams: 120,
    allergens: [],
  },
  roti: {
    calories: 297,
    protein: 9,
    carbs: 50,
    fat: 6,
    sugar: 1,
    fibre: 4,
    avgPortionGrams: 40,
    allergens: ["wheat"],
  },
  chapati: {
    calories: 297,
    protein: 9,
    carbs: 50,
    fat: 6,
    sugar: 1,
    fibre: 4,
    avgPortionGrams: 40,
    allergens: ["wheat"],
  },
  paneer: {
    calories: 265,
    protein: 18,
    carbs: 3,
    fat: 20,
    sugar: 2,
    fibre: 0,
    avgPortionGrams: 50,
    allergens: ["milk"],
  },
  salad: {
    calories: 35,
    protein: 2,
    carbs: 6,
    fat: 0.3,
    sugar: 3,
    fibre: 2,
    avgPortionGrams: 100,
    allergens: [],
  },
  chicken: {
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    sugar: 0,
    fibre: 0,
    avgPortionGrams: 100,
    allergens: [],
  },
  egg: {
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    sugar: 1,
    fibre: 0,
    avgPortionGrams: 50,
    allergens: ["egg"],
  },
  biryani: {
    calories: 180,
    protein: 8,
    carbs: 25,
    fat: 6,
    sugar: 1,
    fibre: 1.5,
    avgPortionGrams: 200,
    allergens: [],
  },
  sambar: {
    calories: 80,
    protein: 4,
    carbs: 12,
    fat: 2,
    sugar: 2,
    fibre: 3,
    avgPortionGrams: 150,
    allergens: [],
  },
  curd: {
    calories: 98,
    protein: 3.5,
    carbs: 4.7,
    fat: 4.3,
    sugar: 4.7,
    fibre: 0,
    avgPortionGrams: 100,
    allergens: ["milk"],
  },
  yogurt: {
    calories: 98,
    protein: 3.5,
    carbs: 4.7,
    fat: 4.3,
    sugar: 4.7,
    fibre: 0,
    avgPortionGrams: 100,
    allergens: ["milk"],
  },
  banana: {
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    sugar: 12,
    fibre: 2.6,
    avgPortionGrams: 120,
    allergens: [],
  },
  apple: {
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    sugar: 10,
    fibre: 2.4,
    avgPortionGrams: 150,
    allergens: [],
  },
  bread: {
    calories: 265,
    protein: 9,
    carbs: 49,
    fat: 3.2,
    sugar: 5,
    fibre: 2.7,
    avgPortionGrams: 30,
    allergens: ["wheat"],
  },
  poha: {
    calories: 110,
    protein: 2.5,
    carbs: 22,
    fat: 1.5,
    sugar: 1,
    fibre: 1.2,
    avgPortionGrams: 120,
    allergens: [],
  },
  upma: {
    calories: 140,
    protein: 3.5,
    carbs: 24,
    fat: 4,
    sugar: 1,
    fibre: 2,
    avgPortionGrams: 150,
    allergens: [],
  },
  vada: {
    calories: 250,
    protein: 6,
    carbs: 28,
    fat: 13,
    sugar: 1,
    fibre: 2,
    avgPortionGrams: 50,
    allergens: [],
  },
  pakora: {
    calories: 280,
    protein: 6,
    carbs: 25,
    fat: 18,
    sugar: 2,
    fibre: 3,
    avgPortionGrams: 40,
    allergens: ["wheat"],
  },
  fish: {
    calories: 120,
    protein: 22,
    carbs: 0,
    fat: 3,
    sugar: 0,
    fibre: 0,
    avgPortionGrams: 100,
    allergens: [],
  },
  "aloo paratha": {
    calories: 290,
    protein: 7,
    carbs: 42,
    fat: 11,
    sugar: 2,
    fibre: 3,
    avgPortionGrams: 100,
    allergens: ["wheat"],
  },
  paratha: {
    calories: 290,
    protein: 7,
    carbs: 42,
    fat: 11,
    sugar: 2,
    fibre: 3,
    avgPortionGrams: 80,
    allergens: ["wheat"],
  },
};

export function calculateNutrition(name: string, grams: number) {
  const key = name.toLowerCase().trim();
  const data = NUTRITION_DB[key] || {
    calories: 150,
    protein: 5,
    carbs: 20,
    fat: 5,
    sugar: 2,
    fibre: 2,
    avgPortionGrams: 100,
    allergens: [],
  };

  const factor = grams / 100;

  return {
    name: name.charAt(0).toUpperCase() + name.slice(1),
    estimatedGrams: Math.round(grams),
    calories: Math.round(data.calories * factor),
    protein: +(data.protein * factor).toFixed(1),
    carbs: +(data.carbs * factor).toFixed(1),
    fat: +(data.fat * factor).toFixed(1),
    sugar: +(data.sugar * factor).toFixed(1),
    fibre: +(data.fibre * factor).toFixed(1),
    allergens: data.allergens,
  };
}

export function getAveragePortion(name: string): number {
  const key = name.toLowerCase().trim();
  return NUTRITION_DB[key]?.avgPortionGrams || 100;
}
